### ISSUE TITLE
Receiver design improvement

### ISSUE THREAD

**Issue by KSExtrez** [Eastrall/LiteNetwork#28]
## Problem
Since we introduce `ReceiveStrategyType` we make a lot of checks on `LiteReceiver` and `LiteReceiverConnectionToken` when to we process message:

```csharp
if (ReceiveStrategyType == ReceiveStrategyType.Queue)
{
  //  Why we do this a lot times?
}
```

I think that this is an anti pattern design, it also difficult the implementation if we try to add another `ReceiverStrategy` in the future.

## Target design

![image](https://user-images.githubusercontent.com/45128933/101829012-f9f75080-3af7-11eb-8b58-310e9be66262.png)

On the target design we isolate the `ProcessReceivedMessages`, so each `ILiteConnectionToken` implementation is responsable to manage how to process the messages.
`LiteReceiver` is responsable to creates a new `ILiteConnectionToken` implementation: 

```csharp
public void StartReceiving(ILiteConnection connection)
{
    ILiteConnectionToken token;
    if (ReceiveStrategy == ReceiveStrategyType.Default)
    {
        token = new LiteDefaultConnectionToken(connection, ProcessReceivedMessage);
    }
    else
    {
        token = new LiteQueuedConnectionToken(connection, ProcessReceivedMessage);
    }
    SocketAsyncEventArgs socketAsyncEvent = GetSocketEvent();
    socketAsyncEvent.UserToken = token;

    ReceiveData(token, socketAsyncEvent);
}
```
Now we can implement new Strategies or maintain one too easy.

**Comment by Eastrall** [comment]
I like the idea. This will open the possibilities for implementing new receive strategies in the futur.
