### ISSUE TITLE
Library shipping process

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/LiteNetwork#36]
I'd like to discuss a topic about the library's shipping process to NuGet. There are actually two possibilities and both have pros and cons.

## Option 1

This option is by far the simpliest one. It consists in shipping the library as a **single** package, including the Client, Server and Protocol libraries.
It makes it very easy to manage versionning and automatic deployement throught a continuous delivery process.

## Option 2

Ship the package as multiple packages, like Microsoft and ASP.NET Core does for its libraries. This option can be a little difficult to handle because it requires a particular workflow to update the packages.
For example, if we have the versions 1.0.1, and we make a important hot fix to the server part, we will to update the server package version to 1.0.2 and the other libraries will stay at 1.0.1. This may cause some version deltas.

---

I'd like your thoughts about the different options so I can decide which on to use for the project.
Thanks

**Comment by KSExtrez** [comment]
I think that the option 2 it's better, it can be more difficult but, it give a differents options to use our library, maybe someone just want to use a protocol library and don't want use server or client library

**Comment by Eastrall** [comment]
Thanks for your feedback @KSExtrez. I also think this might be the best solution but it could be tricky to setup cause if you update the server's package, you will need to update the client and protocol version too.

**Comment by KSExtrez** [comment]
Sure, i really don't know how to setup this, i did a little search in dotnet source code and i found this [wiki](https://github.com/dotnet/winforms/wiki/HowTo:-create-a-release), it looks that they create a `dotnet-maestro` that ensure update the .net packages versions
i'll check the source code and wiki in detail for get more information about solve this problem 😊

**Comment by Simusharp** [comment]
I would think option 2 is better. It helps keeps user project smaller.
