### ISSUE TITLE
Accessing the current connection when processing packets

### ISSUE THREAD

**Issue by EDlTz** [Eastrall/LiteNetwork#44]
Firstly, thanks for making the library it's very simple to use.

The only limitation I've encountered is being able to access the current connection when processing packets since the protocol I'm working with has a different encryption key per session so I won't know the packet length to process the packet.

Looking at the current code I propose adding the `ILiteConnection` to the `LiteDataToken` class so it can be accessed in the below functions. The other option is passing the connection as a parameter to both functions, let me know what you think!

https://github.com/Eastrall/LiteNetwork/blob/8770dace57e615d563f3078963dfb469dbbfd0a7/src/LiteNetwork/Protocol/Abstractions/ILitePacketProcessor.cs#L39
https://github.com/Eastrall/LiteNetwork/blob/8770dace57e615d563f3078963dfb469dbbfd0a7/src/LiteNetwork/Protocol/Abstractions/ILitePacketProcessor.cs#L47

### Proposed Changes

LiteDataToken.cs
```c#
/// <summary>
/// Gets the connection attached to the current token.
/// </summary>
public ILiteConnection Connection { get; }

/// <summary>
/// Creates a new <see cref="LiteDataToken"/> instance with a <see cref="ILiteConnection"/>.
/// </summary>
/// <param name="connection">Current connection.</param>
public LiteDataToken(ILiteConnection connection)
{
    Connection = connection;
}
```

LiteDefaultConnectionToken.cs or LiteQueuedConnectionToken.cs
```c#
DataToken = new LiteDataToken(connection);
```

**Comment by Eastrall** [comment]
Hello, thanks for using `LiteNetwork` and opening this issue to help us improve the library! 
In your usecase, it could be interesting to pass the `ILiteConenction` instance to the current packet being processed by the packet processor. I believe you will have to cast the `ILiteConnection` into your own specific user class in order to access its members like encryption key.

Passing it through the `LiteDataToken` doesn't seem like a problem to me, I'm OK with that.
I'll make the ASAP and deploy a new version.

**Comment by EDlTz** [comment]
Thanks for the quick reply!

That's right, here's how I'm casting the connection.

```c#
if (token.Connection is not ServerUser serverUser)
{
    throw new ArgumentException("Token connection is not a ServerUser.");
}

// Example usage
serverUser.RecvSequence++;
```

**Comment by Eastrall** [comment]
@EDlTz PR has been merged and package pushed to nuget. It should be available shortly! 😉 

Feel free to close the issue once you've tested it with your code.

**Comment by EDlTz** [comment]
Thanks a lot! 😀
