### ISSUE TITLE
LiteServerContext

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/LiteNetwork#50]
Based on discussion on issue #49, we are going to introduce a "server-context" for each `LiteServerUser`. This context allows the user to access some methods of the server like, accessing server configuration and broadcast methods.

# API Proposal

## `LiteServerContext`

This context will contains the following methods:

| Type | Name | Description |
|-------|-------|--------------|
| Method | `void SendTo(LiteConnection connection, byte[] buffer)` | sends a packet buffer to the given connection object. |
| Method | `void SendTo(IEnumerable<LiteConnection> connections, byte[] buffer)` |  sends a packet buffer to a list of connection objects. |
| Method | `void SendToAll(byte[] buffer)` | sends a packet buffer to every connected users. |
| Method | `void SendToAll(byte[] packetBuffer, params LiteConnection[] excludedConnections)` | sends a packet buffer to every connectede user except the given ones. |
| Property | `LiteServerOptions Options { get; }` | Get the server options. |

## `LiteServerUser` 

Add a `protected` property to access the context only from classes that implement the `LiteServerUser`.

```csharp
public class LiteServerUser : LiteConnection
{
     protected internal LiteServerContext Context { get; internal set; }
}
```
> ℹ️  We use the `protected internal` field in order to create and assign the context during user creation.

**Comment by Ezrashaw** [comment]
This is nice, but potentially for `SendToAll` could we have an option not to send the `byte[]` to the `LiteServerUser` that the `LiteServerContext` is in. 

I.E. receive a packet, process it, then send it to all clients _but_ the one that sent the original packet.
This is a really useful feature in for example chat apps where the client doesn't need to be resent the message it just sent.

**Comment by Eastrall** [comment]
Yes, I think we could think of an overload like: `SendToAll(byte[] packetBuffer, bool excludeCurrentUser)`.
Thus, we will have:
```csharp
protected void SendToAll(byte[] packetBuffer) => SendToAll(packetBuffer, excludeCurrentUser: true);

protected void SendToAll(byte[] packetBuffer, bool excludeCurrentUser)
{
    // ...
}
```

**Comment by Eastrall** [comment]
Instead of providing a `void SendToAll(byte[] packetBuffer, bool excludeCurrentUser)` method, we will provide a: `void SendToAll(byte[] packetBuffer, params LiteConnection[] excludedConnections)` instead.
This will allow to call the `SendToAll()` method like the following:
```csharp
public class EchoUser : LiteServerUser
{
    public override Task HandleMessageAsync(byte[] packetBuffer)
    {
        var packet = ... ;
        // ...
       Context.SendToAll(packet, excludedConnections: this);
       // OR
       Context.SendToAll(packet, excludedConnections: new[] { this }); // this is in case you want to exclude several users from broadcast.
    }
}
```

Also changed some methods signatures in `LiteServer` and added them into `ILiteServer` for the `LiteServerContext`.

**Comment by Eastrall** [comment]
Merged on `main` branch.
